name: Commit Date
on:
  push:
    paths:
      - 'src/main/java/**.java'
      
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create report file
        run: echo "Hello, World!"
